### ISSUE TITLE
Feature Request: native CSS keys

### ISSUE THREAD

**Issue by msavin** [blakeembrey/free-style#17]
I like this idea, been wanting something like it for a while. I especially like how it's wrapped in an object, since writing CSS basically feels like writing objects.

Would it be possible to support native CSS keys? For example:

```
var STYLE = Style.registerStyle({
  backgroundColor: 'red'
})
```

To

```
var STYLE = Style.registerStyle({
  "background-color": "red"
}) 
```

That way, people can write CSS like they would expect to write it.

**Comment by blakeembrey** [comment]
@msavin This should already work, give it a go :+1:
