### ISSUE TITLE
Badges are broken

### ISSUE THREAD

**Issue by basarat** [blakeembrey/free-style#18]
Might be transient so you can ignore if it works for you :rose:. But the badges are broken: 

![image](https://cloud.githubusercontent.com/assets/874898/12698251/1f3fba50-c7ec-11e5-81c1-8e6915b30718.png)

**Comment by blakeembrey** [comment]
Should fix up soon. Occasionally shields.io is down and takes down 90% of the badges on GitHub with it. E.g. https://img.shields.io/npm/v/free-style.svg?style=flat

**Comment by basarat** [comment]
Cheers :rose:
