### ISSUE TITLE
Remove TypeScript definition ref on npm

### ISSUE THREAD

**Issue by basarat** [blakeembrey/free-style#26]
Thanks for removing this : https://github.com/blakeembrey/free-style/commit/280ae98294bfdf75e4445d7e6fdd1b2ff96d9854 as it was invalid (file is in `/dist` folder)

Please publish to npm whenever (crashes my personal buggy code ... I'll fix that as well) :rose:

**Comment by blakeembrey** [comment]
https://github.com/blakeembrey/free-style/releases/tag/v1.2.1
