### ISSUE TITLE
Question : What is interpolation

### ISSUE THREAD

**Issue by basarat** [blakeembrey/free-style#34]
From https://github.com/blakeembrey/free-style#rules `Tip: Interpolation is not supported with registerRule.`

What is meant by interpolation? Thanks :rose:

**Comment by blakeembrey** [comment]
Ah, I should probably clarify that. It's https://github.com/blakeembrey/free-style#parent-selector-reference. Basically, it's not obvious what `&` would mean with `registerRule`, so support is omitted (because there's no top-level with these rules, unlike keyframes and classnames).

**Comment by basarat** [comment]
Cheers :rose:
