### ISSUE TITLE
Reconsider the API for interpolation

### ISSUE THREAD

**Issue by basarat** [blakeembrey/free-style#37]
I can understand if this should be closed as it can be done in userland quite easily. Neverthless I wanted to leverage your opinion on something like the following for interpolation : 

```ts
interface NestedCSSProperties extends CSSProperties {
  /** Interpolated */
  '&'?: {
    [selector: string]: NestedCSSProperties;
  }
}
```

Example: 

```ts
{
  'color' : 'red',
  '&': {
     ':focus': SomeCSSProperties
  }
}
```

The current implementation is not amenable for typing: 
```tsx
interface NestedCSSProperties extends CSSProperties {
  /** States */
  '&:hover'?: NestedCSSProperties;
  '&:active'?: NestedCSSProperties;
  '&:disabled'?: NestedCSSProperties;
  '&:focus'?: NestedCSSProperties;

  /** Children */
  '&>*'?: NestedCSSProperties;
  '&:first-child'?: NestedCSSProperties;
  '&:last-child'?: NestedCSSProperties;

 /** Others like nth-child cannot be helped :-/ */
}
```

Again, thanks for being so awesome :rose:

**Comment by blakeembrey** [comment]
Briefly, the nice thing about interpolation today is it's free-form and doesn't force a user into building components a specific way. For instance, I can do a selector like `.featured-post &` to interpolate the current selector and change the current style based on a classname on the body, etc. Although not the recommended approach, it's quite useful in places (I imagine it'd mix well with existing codebases also, plus tools like https://modernizr.com/ which add classes for you based on feature support). 

Based on this, I don't think it's possible to do things like that - unless we treat `&` keys as every child is interpolation without a space. The benefit of this is missing from me though. 

Why couldn't every other selector just be this? I think TypeScript should provide the autocompletion anyway once it sees that it's not an array or primitive. If it doesn't, that might an enhancement request, but I'm pretty sure it does 😄 

```ts
[selector: string]: undefined | number | string | (number | string)[] | NestedCSSProperties
```

Is there any other goals, other than simpler auto-completion?

**Comment by basarat** [comment]
> [selector: string]: undefined | number | string | (number | string)[] | NestedCSSProperties

Works like a charm! Thanks :rose: 

![image](https://cloud.githubusercontent.com/assets/874898/19461153/d5f16370-952d-11e6-997a-33dbecab2010.png)

**Comment by basarat** [comment]
> other than simpler auto-completion?

Also error reporting. Thought I'd mention :rose: 

![image](https://cloud.githubusercontent.com/assets/874898/19461415/19d92454-9530-11e6-831a-4c8f06a87147.png)

Thank you for making my life so much easier :heart:
