### ISSUE TITLE
Human readable css names

### ISSUE THREAD

**Issue by irom-io** [blakeembrey/free-style#56]
I  want to do something this:

`var backgroundStyle = Style.registerStyle({
  backgroundColor: 'red'
}, 'scopeName')`

And css class will be named: scopeName_hash

**Comment by blakeembrey** [comment]
Did you read the README? That's how it already works.

**Comment by blakeembrey** [comment]
If there's something you feel is missing from the documentation, feel free to submit a PR. The second argument to `create` can also force development mode so you don't need to set the environment variable.

**Comment by irom-io** [comment]
Yes, i did not see about prefix, cool that it is realised, thanks)
