### ISSUE TITLE
Proposal: Change handlers

### ISSUE THREAD

**Issue by blakeembrey** [blakeembrey/free-style#60]
/cc @basarat, @ajoslin, @jkroso

Free-Style 2.0 removed the change event listeners in favour of a simpler `changeId++` approach. However, this isn't great for the browser re-parsing styles. I'd like to propose adding handlers (not an event system) that will receive style changes and you can sync up with a `<style />` element using `insertRule` and `deleteRule` directly.

* `onAdd(rule, index)`
* `onChange(rule, newIndex, oldIndex)`
* `onRemove(rule, index)`

All you would need to do is propagate this events directly into a `<style />` element instead of resetting the entire `element.textContent` and causing the browser to re-parse and potential FOUC.

**Comment by jkroso** [comment]
I don't really use change events so I'll count myself out; once my app has rendered once it doesn't define any more styles

**Comment by ajoslin** [comment]
Sounds way more performant, I'm on board.

**Comment by blakeembrey** [comment]
All good. It's a backward compatible change (I'll keep `changeId`), just wanted to get some eyes on it. I'll update the issue when it's implemented 😄

**Comment by basarat** [comment]
Note to self: Useage in typestyle : https://github.com/typestyle/typestyle/blob/d4de3659c88f348e1c2220cc405aba62c9db4b04/src/internal/typestyle.ts#L87-L99 /cc @notoriousb1t 

> (I'll keep changeId),

Well be fine then :rose: :heart:

**Comment by ajoslin** [comment]
Non-breaking change is great to hear.
