### ISSUE TITLE
Shorter class names (suggestion)

### ISSUE THREAD

**Issue by namuol** [blakeembrey/free-style#7]
I noticed [`toString(16)`](https://github.com/blakeembrey/free-style/blob/9b03790e4027c3c682ee5bcb316903c108583fb0/src/free-style.ts#L268) is used on a hashed integer to derive unique classnames, but `toString` actually supports a radix as large as 36, which would produce simple lowercase alphanumeric classnames which tend to be approximately 2 characters shorter. Why not use this instead?

**Comment by blakeembrey** [comment]
You're definitely right, but it'd be a breaking change to change the hash output. In fact, I already made that change in https://github.com/blakeembrey/free-style/pull/6 and it'll be part of V1.

**Comment by namuol** [comment]
Ah, cool. Not sure why I didn't think to check that branch! :beers:
