### ISSUE TITLE
Add grid properties to CSS number whitelist?

### ISSUE THREAD

**Issue by mntnoe** [blakeembrey/free-style#70]
Right now, adding the property `gridColumn: 1` will result in `grid-column: 1px` being generated.

Can we add these properties to the CSS_NUMBER whitelist?

I believe these are the relevant properties:

gridArea
gridColumn
gridColumnEnd
gridColumnStart
gridRow
gridRowEnd
gridRowStart

**Comment by blakeembrey** [comment]
Feel free to submit a PR to expedite the process 👍 

If you need a workaround, you can use strings instead of numbers for now.

**Comment by blakeembrey** [comment]
Closed with https://github.com/blakeembrey/free-style/pull/71.
