### ISSUE TITLE
How do I make transitions?

### ISSUE THREAD

**Issue by Frikki** [blakeembrey/free-style#8]
In ordinary CSS, by changing a class name on an element, I am able to specify transition rules. How do I do that with Free-Style?

**Comment by blakeembrey** [comment]
@Frikki This is still pretty much "ordinary CSS", just in JavaScript. It might help if you could give me an example that I can translate for you, but you can just have two classes registered with Free Style which you apply/remove. Free Style itself does not dictate how you add/remove those classes though, what are you using it with?

**Comment by Frikki** [comment]
@blakeembrey Thank you for your response. It was simply my ignorance of how *Free Style* works that made me ask this question. I hadn’t even tried *Free Style* yet. I simply assumed that it would make inline styles on elements. I will close this issue, as it should then be working just fine as ordinary CSS. Btw., I’ll be using *Free Style* with *Cycle.js*.

**Comment by blakeembrey** [comment]
Not a problem at all! It does generate CSS actually, and does its best to optimise the size of that output. It doesn't do inline styles, that was a core decision of the library. You can mix and match any classes generated by Free Style whenever you need them.
